image: docker:24.0.5

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:24.0.5-dind

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  image: node:20-alpine
  tags: 
    - docker
  script:
    - npm ci
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules/

run_tests:
  stage: test
  image: node:20-alpine
  tags:
    - docker
  services:
    - postgres:15-alpine
  variables:
    POSTGRES_DB: akreditasi_stei
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password123
    DATABASE_URL: postgresql://admin:password123@postgres:5432/akreditasi_stei
  script:
    - npx jest --passWithNoTests

deploy-job:
  stage: deploy
  image: docker:24.0.5
  tags: 
    - docker
  environment: production
  script:
    - docker compose up -d --build
  only:
    - main