image: docker:27-alpine

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:27-dind

stages:
  - build
  - test
  - staging
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  image: node:20-alpine
  tags:
    - docker
  script:
    - npm ci

run_tests:
  stage: test
  tags:
    - docker
  script:
    - docker compose up -d postgres-db
    - npx prisma generate
    - npm test
    - docker compose down

migrate_database:
  stage: staging
  image: node:20-alpine
  tags:
    - docker
  script:
    - npm ci
    - npx prisma generate
    - npx prisma migrate deploy
  only:
    - develop

deploy-job:
  stage: deploy
  tags:
    - docker
  environment: production
  script:
    - docker compose up -d --build
  only:
    - main