image: docker:28.0.0-alpine

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:28.0.0-dind

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  image: node:latest
  tags: 
    - docker
  script:
    - npm ci

run_tests:
  stage: test
  tags:
    - docker
  script:
    - docker compose up -d postgres-db
    - npm test
    - docker compose down

deploy-job:
  stage: deploy
  tags: 
    - docker
  environment: production
  script:
    - docker compose up -d --build
  only:
    - main